---
# Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "rapididentity-{{.Values.tenant}}"
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"

  labels:
    app: rapididentity
spec:
  rules:
  - host: {{.Values.tenant}}.idautoengineering.net
    http:
      paths:
      - path: /
        backend:
          serviceName: "rapididentity-{{.Values.tenant}}"
          servicePort: 8081
