# Service
apiVersion: v1
kind: Service
metadata:
  name: rapididentity-{{.Values.tenant}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{.Values.cert_arn}}
    external-dns.alpha.kubernetes.io/hostname: {{.Values.tenant}}.{{.Values.domainName}}.
spec:
  selector:
    app: rapididentity
    tenant: {{.Values.tenant}}
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8081
  type: LoadBalancer
