- job:
    name: job-generator
    scm:
      - git:
         url: https://github.com/simplytunde/tutorial.git
         branches:
          - origin/master
    builders:
      - dsl:
          target: "pipeline1/docker/jenkins/jobs/**/*.dsl"
    triggers:
      - pollscm:
          cron: "H/2 * * * *"
          ignore-post-commit-hooks: True
