- command: yum makecache fast
- name: install pip
  become: true
  yum:
      name: "{{ item }}"
      state: present
  with_items:
      - epel-release
      - python-pip
      - git
      - docker
- name: enable and start docker
  become: true
  service:
    name: docker
    state: started
    enabled: yes

-  name: Download the application from git
   git:
      repo: https://github.com/simplytunde/tutorial.git
      dest: ~/tutorial
      version: master
- name: install python docker
  become: true
  pip:
    name: docker
- shell: pwd && ls ~/tutorial/pipeline1/docker/jenkins
  register: haha
- debug: var=haha
- name: Build image and with buildargs
  command: sudo docker pull blackpearl/jenkins:v1.0
- name: Run docker init
  command: sudo docker swarm init
  args:
    creates: /tmp/docker-init-started
- file:
    path: /tmp/docker-init-started
    state: touch
- name: Start the app
  command: sudo docker run -d -v /var/jenkins:/var/ -p 8080:8080 -p 50000:50000 blackpearl/jenkins:v1.0
  args:
    chdir: "~/tutorial/pipeline1/docker/jenkins"
