version: '3.1'

services:

  main:
    image: tunde/jenkins
    volumes:
      - ~/Documents/dev/docker/jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
