---
# Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "blogapp-{{.Values.site}}"
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"

  labels:
    app: blogapp
spec:
  rules:
  - host: {{.Values.site}}.{{.Values.domainName}}
    http:
      paths:
      - path: /
        backend:
          serviceName: "blogapp-{{.Values.site}}"
          servicePort: 4000
