# Service
apiVersion: v1
kind: Service
metadata:
  name: blogapp-{{.Values.site}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{.Values.cert_arn}}
    external-dns.alpha.kubernetes.io/hostname: {{.Values.site}}.{{.Values.domainName}}.
spec:
  selector:
    app: blogapp
    tenant: {{.Values.site}}
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 4000
  type: LoadBalancer
