podTemplate(label: 'docker',
  containers: [
      containerTemplate(name: 'docker', image: 'docker', ttyEnabled: true, command: 'cat'),
      containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:v1.8.0', command: 'cat', ttyEnabled: true),
      containerTemplate(name: 'helm', image: 'lachlanevenson/k8s-helm:v2.8.2', command: 'cat', ttyEnabled: true)
  ],
  volumes: [
    hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock')
  ]) {

  def image = "jenkins/jnlp-slave"
  node('docker') {
   stage('Upgrade Deployment') {
      git 'https://github.com/simplytunde/tutorial.git'
      if (env.BRANCH_NAME == 'master') {
         container('helm') {
             sh "helm install --name blogapp-prod --set branch=master --set site=prod demo/helm/charts/blogapp/ --namespace prod"
         }
      }else{
        if (env.BRANCH_NAME == 'staging') {
           container('helm') {
              sh "helm install --name blogapp-staging --set branch=staging --set site=staging demo/helm/charts/blogapp/ --namespace staging"
           }
        }else{
           container('helm') {
               sh "helm install --name blogapp-dev --set branch=dev --set site=dev demo/helm/charts/blogapp/ --namespace dev"
           }
        }
      }
    }
    stage('Build and push ECR image') {
      git 'https://github.com/jenkinsci/docker-jnlp-slave.git'
      container('docker') {
        sh "docker build -t blogapp:v1 ."
        docker.withRegistry('https://143464472856.dkr.ecr.us-east-1.amazonaws.com', 'ecr:us-east-1:ecr-aws-credentials') {
           git url: "https://github.com/jenkinsci/docker-jnlp-slave.git"
           docker.image('blogapp').push('latest')
        }
      }
    }

  }
}
